services:
  vaultwarden:
    image: vaultwarden/server:latest-alpine
    container_name: vaultwarden
    ports:
      - "3926:80"
    restart: always
      #environment:
      # - "SIGNUPS_ALLOWED=true"
    volumes:
      - "/opt/vault/vw-data:/data"
